### ISSUE TITLE
Upstream into leaflet.js

### ISSUE THREAD

**Issue by SylvainCorlay** [ghybs/leaflet-defaulticon-compatibility#1]
Hello, great work on this package. This is super useful. We have worked around that limitation in various way but your approach is much nicer.

Have you considered contributing this to LeafletJS core?

cc @davidbrochart

**Comment by ghybs** [comment]
Hi,

Thank you for your nice feedback!

This plugin is actually an offspring of a Leaflet PR.
See https://github.com/Leaflet/Leaflet/issues/4968#issuecomment-483402699 for explanation.

**Comment by SylvainCorlay** [comment]
Many thanks @ghybs !
