### ISSUE TITLE
not working on leaflet 1.6

### ISSUE THREAD

**Issue by stephenjason89** [ghybs/leaflet-defaulticon-compatibility#2]
using laravel mix 5.0.4

**Comment by FaraFara** [comment]
Confirm. On 1.6 not working.

**Comment by ghybs** [comment]
Hi,

Please can you kindly provide the exact libraries, build engines and frameworks that you are using, as well as their version?

Ideally providing a live reproduction example (e.g. using StackBlitz or Codesandbox). That would greatly help in understanding what could be the issue.

Thanks!

**Comment by FaraFara** [comment]
> Confirm. On 1.6 not working.

All works correct. Sorry. My mistake.

**Comment by ghybs** [comment]
Closing due to lack of information to reproduce the issue and inactivity for a long period.
