### ISSUE TITLE
Undefined not found error

### ISSUE THREAD

**Issue by antonazaides** [ghybs/leaflet-defaulticon-compatibility#3]
Hello,

I've stumbled upon this repo searching for the a solution for the much discussed error:
GET data:image/png;base64,iVB ........... YII=")marker-icon-2x.png net::ERR_INVALID_URL

I followed the outlined steps 

```
import 'leaflet/dist/leaflet.css';
import 'leaflet-draw/dist/leaflet.draw.css';
import 'leaflet-defaulticon-compatibility/dist/leaflet-defaulticon-compatibility.webpack.css';
```

And after importing leaflet:
`import 'leaflet-defaulticon-compatibility';
`

And I still get
GET http://localhost:55288/undefined 404 (Not Found)      undefined:1
![image](https://user-images.githubusercontent.com/73165655/99885427-802d1f00-2c3d-11eb-987c-9970aa6193b9.png)

I'm using electron 8.5.2, electron-webpack 2.8.2 and webpack 4.42.1

Thanks a lot!

**Comment by ghybs** [comment]
Hi,

It is difficult to investigate with little details like this.

Please could you make a simple repo that reproduces the issue?

**Comment by antonazaides** [comment]
Yep, I'll try

**Comment by antonazaides** [comment]
Hi, sorry for the inconvenience, after some tweaking I figured out it was a problem with my setup with electron and webpack. 
Thanks!
