### ISSUE TITLE
Working configuration with Rails 6 & Webpacker without Sprockets?

### ISSUE THREAD

**Issue by thomaswitt** [ghybs/leaflet-defaulticon-compatibility#4]
After several hours I haven't been able to get it up and running. Still image errors. 

I yarn added both packages (leaflet and this one).

packs/application.js contains:
```
import L from 'leaflet';
import 'leaflet-defaulticon-compatibility';
```

packs/application.scss contains:
```
import L from 'leaflet';
import 'leaflet-defaulticon-compatibility';
```

No luck.

Has anybody a  config for Rails 6?

**Comment by ghybs** [comment]
Hi, sorry for the late reply. 

Unfortunately I do not use Rails, so I am not able to provide specific help on your issue.

However it looks like you were able to get a solution in https://github.com/Leaflet/Leaflet/issues/6837#issuecomment-822065164 ?

From Lapizistik:

> In packs/application.js (yes, even if these are css files they are imported here):
>
> `import 'leaflet/dist/leaflet.css';`
> `import 'leaflet-defaulticon-compatibility/dist/leaflet-defaulticon-compatibility.webpack.css';`
